image: docker:latest

variables:
  REGION: ap-south-1

  REPOSITORY_URL: 501801247124.dkr.ecr.ap-south-1.amazonaws.com
  REPOSITORY_NAME: filesharing-repo

  UAT_CLUSTER_NAME: fileshare-aws-ecs-cluster
  UAT_SERVICE_NAME: fileshare-service
  UAT_TASK_DEFINTION_NAME: fileshare-springboot:4

  EXECUTION_ROLE: IAM
  TASK_ROLE: IAM


services:
  - docker:19.03.5-dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region "${REGION}")
  - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"


stages:
  - test
  -pre_build
  - build
  -  post_build

test:
  stage: test
  script: echo "Running Test Cases"
  
  pre_build:
  stage: pre_build
    	script:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=501801247124.dkr.ecr.ap-south-1.amazonaws.com/filesharing-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

build:
  stage: build
  script:
  - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

 post_build:
  stage: post_build
  script:
    - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
 